### ISSUE TITLE
Ladder match crash at startup

### ISSUE THREAD

**Issue by geekingfrog** [FAForever/downlords-faf-client#1508] opened 2019-11-13 13:44 UTC
**Describe the bug**
Once matched with someone for 1v1 ladder, game crash with the following log:

```
Failed to setup initial search path.

Program : Z:\home\greg\.faforever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /uef /log /home/greg/.faforever/logs/game.log /gpgnet 127.0.0.1:30422 /mean 1212.68 /deviation 65.6584 /savereplay gpgnet://127.0.0.1:42631/10509631/BlackMelon.SCFAreplay /country GB /numgames 89 /team 1 /players 2

Callstack:
    unavailable.

Last 100 lines of log...

warning: Running "Z:\home\greg\.faforever\bin\init.lua" failed: cannot read init_faf.lua: No such file or directory
         stack traceback:
         	[C]: in function `dofile'
         	Z:\home\greg\.faforever\bin\init.lua(1): in main chunk

```

**To Reproduce**
Get in queue for 1v1 ladder and wait.

**OS**
Linux
The path `Z:\` is mapped to `/` in wine.
Client version: 1.0.0 (and same bug with 1.0.1-RC5)
Custom games work fine, which is really weird since `init.lua` and `init_ladder1v1.lua` are identical (same content, same permissions).

**Comment by betrok** [comment] 2019-11-14 05:05
I think it might be related with #1442. At least I did not face any troubles with ladder for a while.

**Comment by 1-alex98** [comment] 2019-11-23 00:48
@Brutus5000 we need to change this some day. This is the thing u tried to fix and it blew up XD

**Comment by 1-alex98** [comment] 2019-11-23 00:48
Duplicate of some other issue lemme see

**Comment by 1-alex98** [comment] 2019-11-23 00:51
https://github.com/FAForever/faf-java-api/issues/353 you also find a work arround there

**Closed as completed by 1-alex98** 2019-11-23 00:51 UTC
Labels: bug
