### ISSUE TITLE
"Game Could not be joined" - error when trying to join games.

### ISSUE THREAD

**Issue by insidah** [FAForever/downlords-faf-client#2909] opened 2023-02-03 21:51 UTC
**Describe the bug**
When I try to join any game, since the latest patch, it comes up with an error saying that the "Game could not be joined, see error message below"

**To Reproduce**
Every game I try to join.

**Log or error message**
This is my log file:
Client Version: 2023.1.2
java.lang.Error: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.lang.String.decodeWithDecoder(String.java:1212)
	at java.base/java.lang.String.newStringNoRepl1(String.java:786)
	at java.base/java.lang.String.newStringNoRepl(String.java:738)
	at java.base/java.lang.System$2.newStringNoRepl(System.java:2390)
	at java.base/java.nio.file.Files.readString(Files.java:3369)
	at com.faforever.client.mod.ModService.readPreferencesFile(ModService.java:313)
	at com.faforever.client.mod.ModService.readActiveMods(ModService.java:329)
	at com.faforever.client.mod.ModService.enableSimMods(ModService.java:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:699)
	at com.faforever.client.mod.ModService$$SpringCGLIB$$0.enableSimMods(<generated>)
	at com.faforever.client.game.GameService.lambda$joinGame$10(GameService.java:332)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.faforever.client.task.CompletableTask.lambda$new$2(CompletableTask.java:19)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1359)
	at javafx.concurrent.Task.setState(Task.java:725)
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Task.java:1437)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at java.base/java.lang.String.decodeWithDecoder(String.java:1205)
	... 38 more

**Expected behavior**
Game should start and bring me into the lobby, but it doesn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/123219279/216717550-20216151-78b7-42f6-8af3-c4bc3c465e51.png)

**OS**
Windows 10

**Comment by Sheikah45** [comment] 2023-02-03 21:56
Duplicate of #2905

**Closed as not planned** 2023-02-03 21:56 UTC
Labels: bug

**Comment by insidah** [comment] 2023-02-03 23:50
What do you mean this isn't planned?
