### ISSUE TITLE
Ranked queue animation is CPU intensive

### ISSUE THREAD

**Issue by n-rook** [FAForever/downlords-faf-client#1568] opened 2020-01-29 21:52 UTC
**Describe the bug**
When I queue for 1v1 ladder, my CPU usage goes up by a lot. It goes down again if I navigate away to another tab. I think the animation is using a lot of CPU.

It reminds me of this famous npm bug https://github.com/npm/npm/issues/11283.

**To Reproduce**
Queue for 1v1 ladder and view the CPU usage of the client.

**Expected behavior**
Queuing for ladder should not significantly affect CPU usage.

**OS**
Linux or Windows

**Comment by Katharsas** [comment] 2020-01-29 21:55
Duplicate of https://github.com/FAForever/downlords-faf-client/issues/1371

**Closed as completed by Katharsas** 2020-01-29 21:55 UTC
Labels: bug, duplicate
