### ISSUE TITLE
Rate map after game finishes

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#2528] opened 2022-01-17 06:38 UTC
Map vaults require player activity to create some collections of maps that the player chooses. Idea is to make collections of maps based on several criteria like **player's choice**, **most rated maps**. I would like to try to implement suggestions for hosting for players in a new client, so more ratings are needed xD. Currently map vaults is not visited as actively as it should be.

**Comment by Sheikah45** [comment] 2022-01-17 12:24
Duplicate of #1003

**Closed as completed** 2022-01-17 12:25 UTC
