### ISSUE TITLE
prevent users from using the wrong game path (again)

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1355] opened 2019-07-21 06:31 UTC
had a user this week on discord who couldn't run the game
he managed to select vanilla supcom for the base game install instead of forged alliance

please don't allow users to select the vanilla supcom install directory (tested myself and the client doesn't throw an error when trying to do so in 0.10.7)

**Comment by Geosearchef** [comment] 2019-07-21 08:23
How can we distinguish the two? Currently the client just looks for the bin folder.

**Comment by Brutus5000** [comment] 2019-07-21 08:25
Vanilla has a `SupremeCommander.exe` in bin and FA has a `ForgedAlliance.exe` in bin.
You could even tell the user: hey looks like you selected Supreme Commander vanilla, not Forged Alliance

**Comment by Katharsas** [comment] 2019-07-21 11:52
Duplicate of https://github.com/FAForever/downlords-faf-client/issues/1100
Since the steam files are static, we could just check that some files have expected hashes? This way we also would notice if the steam install is modded / patched.

**Comment by 1-alex98** [comment] 2020-03-04 14:43
@PhilipJFryFAF @speed2CZ is there a use case where u select the vanilla game for coop??? I need to know because otherwise I can quickly do this here

**Comment by 1-alex98** [comment] 2020-03-04 14:53
Ok so I checked @Brutus5000 and 

> Vanilla has a SupremeCommander.exe in bin and FA has a ForgedAlliance.exe

is wrong my FA game has an EXE called SupremeCommander.exe

**Comment by 1-alex98** [comment] 2020-03-04 14:54
So how do I detect somebody selects the vanilla game. I don't have the vanilla game some somebody needs to tell me preferably I would like to check for the existence of a file that is not there is the noral FA installation.

**Comment by Slothologist** [comment] 2020-03-04 19:57
Good candidates would be the "Microsoft.VC80.CRT.manifest" or the "LuaPlus.exe" file of the vanilla bin folder. Both are not present in the FA bin folder. 
The "steam_api.dll" and "steam_appid.txt" on the other hand are not present in the vanilla folder.

**Comment by 1-alex98** [comment] 2020-03-04 21:44
Well there are also valid not steam version of the game so those files are probably a bad idea

**Comment by 1-alex98** [comment] 2020-03-04 21:45
Or maybe use the hash of the vanilla exe.... not sure if that's a good idea. There are probably different version of the game

**Comment by Slothologist** [comment] 2020-03-04 23:38
Isn't a steam version of the game required nowadays, due to the multiacc issue? If not, you are of course right.

Super low effort solution would be to just check the path given by the user itself. If the user did not manually rename the folders, they should be 
some/path/where/you/install/your/games/Supreme Commander/bin
versus
some/path/where/you/install/your/games/Supreme Commander Forged Alliance/bin
So if your path ends with "Forged Alliance/bin" you are almost certainly in the right folder.

You could also check files in the movies folder, these are (almost?) entirely different.
The file size of the SupremeCommander.exe also seems vastly different, 0.5 MB (vanilla) versus 13MB (FA).

Hashing sure is the way to go if you also want to ensure an unaltered game (or want to remind the user he has a altered game which will not work). Would you then just hash the main .exe or the whole game folder, which could take a while (especially on HDD's)? Afaik most if not all normal mods were/are installed to the supcom/mods folder, so I don't think that they have an impact on FAF at all.
One should consider that updates to old games on steam are super rare, but not unheard of (see e.g. https://steamcommunity.com/discussions/forum/0/1780513643846438019/ ), so if a given hash is hard-coded in, a steam update could break this overnight.
Still, hashing looks like the way to go, especially if you want to combat #1100 as well, as @Katharsas pointed out. False negatives could either way be mitigated by just warning the user instead of absolutely disallowing them to use a "modified" game folder.

**Comment by 1-alex98** [comment] 2020-03-05 09:42
Well yes the folder name is probably a good indicator as well and no steam version is not required, steam lining is required! There is a difference. Users are not forced to install via steam they just need to own it in steam

**Comment by 1-alex98** [comment] 2020-03-05 09:44
@Slothologist so u own the vanilla game on steam? Can you provide me the SHA-2 hash of it? Like only the exe

**Comment by Geosearchef** [comment] 2020-03-05 10:01
SupCom
CRC-32: 715FBE24   (We do not need the one way property of a hash function and CRC should be way faster)
SHA256: 1AFBCD0CA85546470660FA8AC09B230E870EC65C8D1B33FEB6731BB5D4C366C5

**Comment by 1-alex98** [comment] 2020-03-05 10:07
CRC32 does not prevent collisions by design which is probably not bad since there are only a few files that we will ever run the chec on but I think SHA is at least in theory more fitting.

**Comment by Geosearchef** [comment] 2020-03-05 10:09
CRC is built to detect bit errors, so yes, we don't have single bits, go for a longer checksum/hashfnct.

**Comment by 1-alex98** [comment] 2020-03-05 11:18
@Geosearchef @Slothologist go test the PR ;) I included the hash from Geosearched but we could also include further hashes

**Comment by 1-alex98** [comment] 2020-03-05 11:19
I also avoided that the user selects the faf ProgrammData one because I also had reports about users selecting that one

**Comment by Slothologist** [comment] 2020-03-05 16:02
Sadly this does not work (at least on linux).
The hashes created by the function differ from the actual hashes. Note that sha256sum gives the same hash value @Geosearchef has provided (via command line).
Because of that I never run into the "vanilla exe detected" case.

Edit: I fixed that in https://github.com/FAForever/downlords-faf-client/compare/bugfix/%231594-ask-for-game...Slothologist:bugfix/%231594-ask-for-game

**Closed as completed** 2020-03-11 22:16 UTC
Labels: beginner-friendly
