### ISSUE TITLE
FAForever client update 2022.8.0

### ISSUE THREAD

**Issue by GastonMelo** [FAForever/downlords-faf-client#2783] opened 2022-08-21 15:54 UTC
**Describe the bug**
I installed FAF client according to https://youtu.be/Rv3ZXA4FNFk and it worked like a charm!! A few days ago I tried to play the game and it says "update to version 2022.8.0". The update gets stuck at 100% and nothing else happened. I tried downloading the 2022.8.0 tar from releases and start the game from console but this messages came out " java.lang.ClassNotFoundException: install4j.com.faforever.client.Main"

![Screenshot_20220821_124252](https://user-images.githubusercontent.com/42498839/185799163-66b1281d-8981-4b3c-91b2-2c9b6fad53e2.png)

**OS**
Linux opensuse Tumbleweed
Things that I tried:
1)changing java version
2) donwloading realese 2022.8.0 and from console launching the game

Any ideas?
Gastón

**Comment by MrRowey** [comment] 2022-08-21 15:55
the Auto download doesn't work well with Linux best thing to do is to do it get the new version from the GitHub

**Comment by Sheikah45** [comment] 2022-08-21 15:55
Auto update is broken for linux. Duplicate of #1026 , you need to just download and install from the release here or extract the tar.gz that is downloaded.

**Closed as completed by Sheikah45** 2022-08-21 15:55 UTC
Labels: bug, linux
