### ISSUE TITLE
Stop chat user listener garbage collection

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2102] opened 2021-01-05 01:14 UTC
Listeners for chat user change are getting garbage collected and stopping chat user list updates

**Comment by micheljung** [comment] 2021-01-05 15:24
Is this related to, or a duplicate of #2061?

**Comment by Sheikah45** [comment] 2021-01-05 15:37
This is somewhat related to #2061. I wasn't able to duplicate #2061 but I know that this garbage collection causes other issues with all the chat user list properties

**Closed as completed** 2021-01-07 00:27 UTC
Labels: bug
