### ISSUE TITLE
Cannot create a custom game even if you are not in all queues

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2435] opened 2021-12-09 16:16 UTC
1. Join to all queues (1v1, 2v2)
2. Leave all queues.
3. Try to create a custom game

Message will be displayed: `Please leave all queues before joining a custom game`

Client version: 2021.10.0

**Comment by Sheikah45** [comment] 2021-12-09 16:17
Duplicate of #2410. Fixed in 2021.11.0

**Closed as completed** 2021-12-09 16:17 UTC
Labels: bug
