### ISSUE TITLE
map review discussion

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1535] opened 2019-12-22 13:28 UTC
If I'm using it wrong please tell me ;)

Yesterday I saw the review of drunk_robot and wanted to reply (not vote).
While doing so I was wondering about 3 things...
![dfc_map_info_issues_questions](https://user-images.githubusercontent.com/28671151/71322177-fde42a00-24c4-11ea-9c07-9409f4ed8917.png)

**1) Could his statement have been avoided if he had had access to the complete description?**
The map description is to long to be displayed #1137 
Unfortunately, the link to my map information is cut off. Pls fix this <§

**2) How do we treat false accusations?**
I would like to be able to remove such posts, or answer in such a way that it is clear that I am referring to this post.

**3) How do I reply, without voting?**
Maybe we should separate the voting (0-5 stars) and the review/reply. This way people can comment multiple times without voting, which is especially helpful for the map maker. But we still need to ensure that a player can only vote once.

**Comment by 1-alex98** [comment] 2019-12-23 15:00
Well this seems a valid suggestions, please note the following tho.
1. Seems to be a bug
2. Well we lack the resources to implement deleting ratings, (we are able to delte them in database, which is really time consuming, so I bet we would only do it if a rating contains harsh insults). We have way more severe issues to deal with. Tho this is an open source project if you want this you could look into implementing it yourself or find somebody that wants to(Could possibly put a bounty on it 🤔 ).
3. Commenting without giving a review is not possible on purpose because in ancient times when it was possible ppl used to have arguments in the map/mod vault which should be avoided. Which needed moderation etc. And well in the end everything was spammed

So it comes down to point 1)

**Comment by 1-alex98** [comment] 2019-12-23 15:03
So as u already have another issue for point 1 I am closing this feel free to comment and argue here tho

**Closed as completed by 1-alex98** 2019-12-23 15:03 UTC

**Comment by badbwoi** [comment] 2020-01-24 12:21
Hey @axel1200 thanks for the reply.

I'm looking forward to #1137 getting fixed <3


Just some thoughts on the map review thingy...

2a. Delete comments
I'm thinking about giving permission for deleting a comment to map maker (and moderators). So the map maker can do the main work clean/delete the comments. With this there is no need to reply to some posts e.g. 3, but it only makes sense if only the comment can be deleted.

2b. Deleting ratings
well if a map maker can delete a rating it does not make much sense too have it - ABUSE ;)

2c. Delete comment and rating
It would be nice to give this permission to moderators.
map maker cannot abuse it and it simply clears a rating and comment from one person

**Comment by 1-alex98** [comment] 2020-02-09 00:11
Still I dont think we really need this. Well go ahead code it sounds good. But I guess we have way more important stuff to do

**Comment by badbwoi** [comment] 2020-02-09 09:23
That sound good! thx @axel1200 

But maybe its not even worth your time (for now) ...
Is it a bug or a feature that the map rating/review is not migrated when u upload a new map version?
![image](https://user-images.githubusercontent.com/28671151/74099631-1d431f00-4b26-11ea-928f-8f4d8fcc38db.png)

**Comment by 1-alex98** [comment] 2020-02-09 22:23
ehm no idea Well I thnk it is neither. It is not a bug because it was intended on the other hand it is suboptimal i guess

**Comment by badbwoi** [comment] 2020-02-16 09:45
I opened a new issue for the map review/rating migration #1581
