### ISSUE TITLE
webkit crash on 1.1.9

### ISSUE THREAD

**Issue by singinwhale** [FAForever/downlords-faf-client#1846] opened 2020-08-01 12:26 UTC
When I launch the client, I get up to the "Logging in..." throbber. Then the program silently crashes. I attached the logs for reference:

[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/5010337/downlords-faf-client.log)
[hs_err_pid34536.log](https://github.com/FAForever/downlords-faf-client/files/5010338/hs_err_pid34536.log)
[hs_err_pid12572.log](https://github.com/FAForever/downlords-faf-client/files/5010347/hs_err_pid12572.log)
[hs_err_pid29796.log](https://github.com/FAForever/downlords-faf-client/files/5010348/hs_err_pid29796.log)

on first glance it seems, that the webkit thread crashes. Is there any crazy HTML code on the front page maybe?

**I tried the following fixes:**
I tried a full reinstall already but that did not help.

In the downlords-faf-client.log there are some errors thrown by a certain map. I deleted that map and tried again but that is not the cause.

**Comment by 1-alex98** [comment] 2020-08-01 15:01
So u can not launch because of this right... There is a client.prefs that says what tap u start in if you set it to PLAY then it does not open news and hence does not crash... C:\Users\Alexander\AppData\Roaming\Forged Alliance Forever
![grafik](https://user-images.githubusercontent.com/19996713/89104299-a9206e80-d418-11ea-93e3-5f9a9c4d8dc7.png)

**Comment by 1-alex98** [comment] 2020-08-01 15:02
Yes the browser is crap but some ppl desperately wanted such a website

**Comment by singinwhale** [comment] 2020-08-01 15:07
Interestingly, I can now start the client normally again. With or without changing the default tab. 
Maybe they fixed the webpage. 
Would be cool however if the client would not crash because of something like this.

**Comment by 1-alex98** [comment] 2020-08-01 15:09
This is impossible this is an Access Exception. The OS will force the closing of the JVM. There is not way we can possible catch such things. We could make a java bug report but without a way to reproduce they are not really gonna care about it.

**Comment by 1-alex98** [comment] 2020-08-01 15:10
No reproducable

**Closed as completed by 1-alex98** 2020-08-01 15:10 UTC
