### ISSUE TITLE
Idea: Ability to create mod groupings

### ISSUE THREAD

**Issue by insidah** [FAForever/downlords-faf-client#2896] opened 2023-01-21 01:47 UTC
Hi all,

Currently it has been a bit frustrating when I try and figure out what mods worked well with previous games I hosted, not to mention that when I join a game, it remembers and automatically selects the last used mods for the next game.

What I'd like to propose, is if we can save mods as a grouping with a name, that is - if I want to play final rush, I can make a few different combo's of mods, with various names like "low upgrades and t3 hives" which I can then add mods to, which reflect my description.

Hopefully this makes sense - and its not a hard idea to implement. 

Thank you :)

**Comment by Sheikah45** [comment] 2023-01-21 01:50
I believe this is a duplicate of #1804 so will close and reference that issue. If you think it is separate please reopen with an explanation.

**Closed as completed by Sheikah45** 2023-01-21 01:50 UTC
