### ISSUE TITLE
Malformed tooltips of Game Tiles

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#625] opened 2017-11-01 17:54 UTC
If there is only one team the tooltip is to big, that looks awful

**Comment by axel1200** [comment] 2018-01-12 21:14
Thts the problem: 

> Setting the preferred number of columns and/or rows in the TilePane determines the calculation for the prefWidth and prefHeight values for that tile pane. 

For the tile pane of teams!
But I can not change anything about it....

**Comment by micheljung** [comment] 2018-01-15 10:17
As we saw yesterday, it's not just this. The tooltip is twice as large than it needs to be. Cause unknown.

**Comment by Katharsas** [comment] 2019-07-03 20:19
Closed duplicate of #804

**Closed by Katharsas** 2019-07-03 20:19 UTC
Labels: bug
