### ISSUE TITLE
Message notifications appear, but no messages to be found

### ISSUE THREAD

**Issue by Garanas** [FAForever/downlords-faf-client#3012] opened 2023-07-16 16:54 UTC
**Describe the bug**
It appears I keep receiving notifications in chat messages in the client, but I can't see the message.

**To Reproduce**
Try to have a conversation with someone, especially PMs but also Aeolus doesn't appear to always update.

**Log or error message**
There are no logs that indicate something went wrong. I get a Windows notification (the red little circle with a number in it), I sometimes even hear a sound but then there's ... nothing. Sometimes someone sends me a message, the private chat tab is open but there's no message.

**OS**
Windows

**Comment by Garanas** [comment] 2023-07-18 20:43
![image](https://github.com/FAForever/downlords-faf-client/assets/15778155/5b352d87-94ba-45ff-aba8-3eb93ef90816)

As an example while being idle all day, they're all empty but the chats exist and I did receive the notifications (red number in app icon)

**Comment by Garanas** [comment] 2023-07-23 06:10
I've received messages in Discord about the same bug, so it is not just me.

**Comment by ChessBerry** [comment] 2023-07-23 21:16
Yeah I have the same problem, Has been around for at least a week as well

**Comment by ChessBerry** [comment] 2023-07-28 20:16
Also note this, maybe relevant(?) correlation with the weird behavior when closing the client:
https://github.com/FAForever/downlords-faf-client/issues/3016#issuecomment-1656281931

**Comment by ChessBerry** [comment] 2023-07-29 13:29
Soo, had some time today to debug this a bit with @Garanas and Man_on_the_Moon.

In short: Not everyone seems to be effected by the bug in the same way. Some people, like @Garanas, Mize and me have the first (or more) messages we get sent by anyone vanish. Some others seem, like Man_on_the_Moon, seem(?) to have the chat working correctly for everyone, but people like the first group, and if they chat with them they have the same vanishing message problem. I'm not certain that these two groups truly experience different client behavior though, could be other factors explaining it.

The bug is very easy to reproduce though: Open a new chat with someone you haven't chatted this session yet, send them a message, and they'll have the chat window open but no message shown, exactly as jip describes above. In fact, if you send the first couple messages fast enough, you can even make more than one message disappear. Here for example I sent Jip the first msg twice and neither was shown to him:
![](https://cdn.discordapp.com/attachments/785995280498819103/1134826707199729705/Screenshot_260.png)
![](https://cdn.discordapp.com/attachments/785995280498819103/1134826417163612300/image.png)

It appears that the "vanishing" messages do actually arrive normally, as the message notification sound plays and the message preview of the content gets shown correctly too (most of the time?). Just the display of the messages in the chat window seems to be broken.

Some more testing with Man_on_the_Moon demonstrated that the bug is present in the 2023.6.0 and the 2023.7.0 versions of the client, but does not seem to exist in the 2023.5.0 version. 
Specifically, it seems that if you are on the 2023.5.0 version you can recieve messages perfectly fine but if messages you send appear for the other person depends their client version.

I'm not 100% on the 2023.5.0 actually not having this bug as I haven't tested it often enough and with enough people, but it seems to be promising. The release of 2023.6.0 possibly introducing the bug would also fit the time frame of the bug appearing "a couple weeks ago".

Some screenshots:

Sending messages from 2023.5.0 (CheeseBerry) to 2023.7.0 (Man_on_the_Moon) doesn't work, the first "x" message is missing:
![](https://cdn.discordapp.com/attachments/907748758899548193/1134833384565243914/Screenshot_268.png)
![](https://cdn.discordapp.com/attachments/907748758899548193/1134833215824211968/image.png)

This is reproducible:
![](https://cdn.discordapp.com/attachments/907748758899548193/1134832246482808892/Screenshot_266.png)
![](https://cdn.discordapp.com/attachments/907748758899548193/1134832192963477594/image.png)

Sending messages from 2023.7.0 (Man_on_the_Moon) to 2023.5.0 (CheeseBerry) does work, all 7 messages arrived:
![](https://cdn.discordapp.com/attachments/907748758899548193/1134831558663082046/image.png)
![](https://cdn.discordapp.com/attachments/907748758899548193/1134831862108401714/image.png)

After Man_on_the_Moon downgraded to 2023.5.0 as well, both sending and receiving messages works in both directions:
![Screenshot_270](https://github.com/FAForever/downlords-faf-client/assets/90977374/1a8f1610-1d05-4a5a-a92a-e74fec9db012)
![](https://cdn.discordapp.com/attachments/907748758899548193/1134834134661988375/image.png)

**Comment by ChessBerry** [comment] 2023-07-29 13:30
@Garanas Could you downgrade to 2023.5.0 as well and see if that fixes it for you?

**Comment by ChessBerry** [comment] 2023-07-30 22:20
Well so much for that approach xd
![Screenshot_273](https://github.com/FAForever/downlords-faf-client/assets/90977374/faabb19a-fbc4-4de7-bba6-44ff7a0e654b)

**Comment by Sheikah45** [comment] 2023-08-04 23:59
Should be fixed in 2023.7.1

**Closed as completed by Sheikah45** 2023-08-04 23:59 UTC
Labels: bug
