### ISSUE TITLE
Right click menu closes super fast

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1639] opened 2020-03-28 21:33 UTC
Haven't found an issue on this one, and multiple people reported having the same problem...
Like the title says, the right click menu in chat (user context menu) closes extremely fast after opening, making it barely usable.

screenshot in case it wasn't clear what I was talking about:
![grafik](https://user-images.githubusercontent.com/61892809/77834303-aac0e980-713b-11ea-8dda-f089c16a35c2.png)

**Comment by Askaholic** [comment] 2020-03-28 21:35
I think it's because the menu is closed whenever the user list is updated. And when there are 2000 people online the user list changes almost constantly.

As I see it there are basically 2 options:
- Don't close the context menu when the user list changes or
- Don't change the user list while the context menu is open

You might be able to work around this as a user by first filtering the user list for the player who's context menu you want to open before right-clicking. But this is obviously pretty annoying.

**Comment by 1-alex98** [comment] 2020-03-28 22:26
I think that is a duplicate

**Comment by 1-alex98** [comment] 2020-03-29 00:23
Duplicate of https://github.com/FAForever/downlords-faf-client/issues/1429

**Closed as completed by 1-alex98** 2020-03-29 00:23 UTC
Labels: bug
