### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1372] opened 2019-07-29 06:23 UTC
log files from the java client (version 0.10.7) are flooded with the following warning/error message:
`java.lang.NullPointerException: null`

example of a log file from a very short session - all i did was log in, open up the play tab and then go back to the chat tab (i assume the error is thrown each time a user switches the tab?)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3440494/downlords-faf-client.log)

this log spam makes log files incredibly annoying to read which in return makes it harder to find bugs

**Comment by Katharsas** [comment] 2019-07-29 12:49
Duplicate of https://github.com/FAForever/downlords-faf-client/issues/1331
(Fixed in 1.0.0)

**Closed as completed by Katharsas** 2019-07-29 12:49 UTC
