### ISSUE TITLE
Allow java versions >15

### ISSUE THREAD

**Issue by Seelengrab** [FAForever/downlords-faf-client#2400] opened 2021-10-19 15:19 UTC
I've run FAF on archlinux with java 17 by commenting out the relevant lines that check the version in the generated run shell script, so I think making gradle generate a new run script that allows higher versions should be fine.

**Comment by Sheikah45** [comment] 2021-10-20 17:56
Duplicate of #2298

**Closed as completed by Sheikah45** 2021-10-20 17:56 UTC
