### ISSUE TITLE
MapGen: can't watch replay with generated map

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1772] opened 2020-06-14 18:33 UTC
![image](https://user-images.githubusercontent.com/11618427/84601091-24848b80-ae7e-11ea-9e67-27e5324883c7.png)
you get this error. From what geo said, this isn't a bug related to map generator, but to the client.

Geosearchef: The map generator is deterministic, given a seed
Geosearchef: It detects and auto downloads the required version based on the map name

**Comment by 1-alex98** [comment] 2020-06-14 20:54
yes might still be map gen bug... gimme log of the client

**Comment by Katharsas** [comment] 2020-06-19 21:44
@axel1200 how can it be a map gen bug?? The mapgen doesnt do anything with replays.

Btw this is trivial to reproduce. Just start a map gen game, go to online replay vault, your replays, try to watch it.
The problem seems to be that the client just looks at the replay json metadata, which contains `"mapname": "None"`, and then throws the error because there is no map. Seems like map name is not correctly saved in replays.

I checked in API, map name is nowhere to be found. The client saves the mapName correctly in local replay files. Maybe a replay server problem?

**Comment by Katharsas** [comment] 2020-06-19 22:37
This is a replay issue for now, but we migh need to make sure to check map names for illegal path/file chars in the future becasue map names could be from untrusted user/source. Keep open for now.

**Comment by Katharsas** [comment] 2020-06-19 23:27
Ok there are multiple problems here:
- The replay server saves "None" into the map name because it sets the map name by finding map filename and getting map name based on that from DB, but DB does not have mapgen maps. This can be fixed by the client reading the mapname directly from the replay instead of the metadata, like it already does for coop maps.
- I am an idiot.

Additionally:
The MapService currently always regenerates mapgen maps instead of checking if they already exist like normal maps and then skipping generation.

**Closed as completed** 2020-07-05 17:47 UTC
Labels: bug, S2 major
