### ISSUE TITLE
Replay vault throws error on using start/endTime condition

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#567] opened 2017-07-13 16:38 UTC
When trying to query for a replay whilst using a criteria like start/endTime, the following Exception is thrown:

```
java.util.concurrent.CompletionException: org.springframework.web.client.HttpServerErrorException: 500 Server Error
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:324)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.web.client.HttpServerErrorException: 500 Server Error
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:83)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:287)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:524)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:511)
	at com.faforever.client.api.FafApiAccessorImpl.getMany(FafApiAccessorImpl.java:501)
	at com.faforever.client.api.FafApiAccessorImpl.findReplaysByQuery(FafApiAccessorImpl.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy63.findReplaysByQuery(Unknown Source)
	at com.faforever.client.remote.FafServiceImpl.findReplaysByQuery(FafServiceImpl.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport$CompletableFutureDelegate$1.get(AsyncExecutionAspectSupport.java:321)
	... 4 more
```

**Comment by Brutus5000** [comment] 2017-07-14 07:23
Can you share the filter statement that was generated? Looks like an inproper API request.

**Comment by micheljung** [comment] 2017-07-14 08:34
This is caused by FAForever/faf-java-api#111

**Comment by micheljung** [comment] 2017-10-07 16:14
Fixed in API, wasn't a client issue.

**Closed by micheljung** 2017-10-07 16:14 UTC
Labels: bug
