### ISSUE TITLE
Add option to use 24-hour notation in chat timestamps

### ISSUE THREAD

**Issue by doodhout** [FAForever/downlords-faf-client#387] opened 2016-10-07 15:44 UTC
Because, you know, some people are completely not familiar with 12-hour timestamps.

**Comment by micheljung** [comment] 2016-10-07 16:03
Absolutely! Duplicate of #240

Thanks for reporting anyway, keep it up.

**Closed by micheljung** 2016-10-07 16:03 UTC
Labels: duplicate

**Comment by doodhout** [comment] 2016-10-07 16:04
I'm sorry, I tried looking for it by using the keywords 'timestamp' (nothing) and 'time' (too much clutter). Next time I'll try to search more thoroughly. ;-)

**Comment by micheljung** [comment] 2016-10-07 16:10
Don't worry, I rather get duplicates than no reports :-)
