### ISSUE TITLE
Mismatch number of players in replay header / live replay info

### ISSUE THREAD

**Issue by Crotalus** [FAForever/downlords-faf-client#2504] opened 2022-01-06 21:53 UTC
**Describe the bug**
I've noticed that the info card for a replay sometime doesn't show all players in a game due to missing metadata 

Example:

The replay metadata header my local replay 16066901 have this team info:
"teams":{"2":["Jacci","vena202020","Alfariy113","ZOORID"],"3":["Crotalus_Bureus","Nooby-pl","parsley53"]}

The replay I download from FAF has correct in this case:
"teams": {"2": ["Jacci", "vena202020", "Alfariy113", "ZOORID"], "3": ["Crotalus_Bureus", "Nooby-pl", "I_EGO_I", "parsley53"]

**OS**
Windows

**Comment by Sheikah45** [comment] 2022-01-06 21:55
Duplicate of #2495

**Closed as completed** 2022-01-06 21:56 UTC
Labels: bug
