### ISSUE TITLE
Sometimes updating information about the lobby stops working.

### ISSUE THREAD

**Issue by GodFuper** [FAForever/downlords-faf-client#2348] opened 2021-09-16 17:34 UTC
**Describe the bug**
When using the second monitor screen on Windows 10. Game information updates stop working.

**To Reproduce**
Well, I started FAF, open the list of games, select any one.
Drag the FAF window to another monitor screen and bring it to the edge of the monitor so that the FAF stretches completely. After that, click on the "Not full-scale" button, next to the cross in the upper right corner.
After that, all the information about the games on the right will not be updated. Fixed to return to full-screen mode.

**Log or error message**
The logs are empty, there is nothing remarkable.

**Screenshots**
<a href="https://gifyu.com/image/Jyze"><img src="https://s9.gifyu.com/images/ANIMATIYe33c34b2c5665f26.gif" alt="ANIMATIYe33c34b2c5665f26.gif" border="0" /></a>

**OS**
Windows 10
(Automatic stretching of the program to full screen seems to have been added after Win 8.)

**Comment by Sheikah45** [comment] 2021-09-17 00:50
Seems like it happens when the window button is clicked and the client windows goes below some minimum size.

**Comment by GodFuper** [comment] 2021-09-17 06:04
I have a main monitor of 1920x1080, and a second monitor of 1360x768. If there are some conditions with the screen size. Then it seems that this is the problem.

**Comment by Sheikah45** [comment] 2021-09-17 11:23
It is not the monitor size it is the actual size of the window. In the gif you showed the updating issue only occurs in my testing when the window is small and elements start to overlap. Still not sure why though.

**Comment by timocov** [comment] 2022-06-26 21:44
I have similar (the same?) problem and it started happening for me maybe a few months ago:

![faf-client-bug](https://user-images.githubusercontent.com/3112183/175834621-20bebc9d-69f2-42d4-8caf-4cc8f35eb6d8.gif)

I don't know what exactly causes this and what the steps to reproduce it exactly, but after some actions (entering a lobby, playing a page) the list of games becomes inadequate:
- it doesn't show the list of all games, looks like only some of them and that a cached ones are displayed
- whenever you click at any game to see a preview it shows a different game
- if you try to apply a sorting it might break the whole list of games
- if you switch to a Tiles view the sorting combobox displays `null` and nothing happens when you try to change it
- reconnecting to both chat and faf doesn't help, the only thing that works for me is restarting the client
- changing a size of the window doesn't help either

I run the client always maximized, have only 1 screen (full hd), 100% zoom on the screen. It looks like the caching problem of items being displayed vs the actual items in the model, but it's my guess. Today I've upgraded to the experimental channel because it became useless to restart a client after every game, but not too sure if it is helping (if it might).

**Comment by timocov** [comment] 2022-06-26 23:14
This is how it is usually looks like for me after a game. Note that in addition to the issues above 1) all the games have wrong preview (but I guess the list is just wrong) 2) I'm unable to click at the items below some point (sometimes I'm able to use arrows on the keyboard, but not always)

![faf-client-bug-2](https://user-images.githubusercontent.com/3112183/175837407-7f0bda83-77a8-402f-bae9-c9b3429a469e.gif)

**Comment by Sheikah45** [comment] 2023-02-20 23:40
Should be fixed with the recent rework of game update processing

**Closed as completed by Sheikah45** 2023-02-20 23:40 UTC
Labels: bug
