### ISSUE TITLE
Add ability to select the number of players on a generated map

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1773] opened 2020-06-14 20:54 UTC
**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Katharsas** [comment] 2020-06-14 21:12
Duplicate of / related to  https://github.com/FAForever/downlords-faf-client/issues/1694

**Comment by Sheikah45** [comment] 2020-07-25 10:27
Implemented in #1803

**Closed as completed by Sheikah45** 2020-07-25 10:27 UTC
Labels: enhancement
