### ISSUE TITLE
launch script does point to set java enviroments on Manjaro/arch

### ISSUE THREAD

**Issue by coreybruce** [FAForever/downlords-faf-client#2413] opened 2021-11-02 05:16 UTC
**Describe the bug**
The launch script does not point to the correct location where java versions are set on Manjaro/Arch and thinks java 16 for example isn't installed.

```
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be 15.
```
For example on Manjaro/Arch we can use the archlinux-java command to set our default version of java

![image](https://user-images.githubusercontent.com/8393780/139790570-2a6b822b-226e-4410-b787-7cfeecbe87c8.png)

**To Reproduce**
Ran the script

**Log or error message**
This is my log file:
```
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be 15.
```

**Expected behavior**
Game runs

**Screenshots**
![image](https://user-images.githubusercontent.com/8393780/139790477-8b68f4b7-61ae-40d4-ba2e-2046aa769951.png)

I even followed the steps from here: https://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux#Set_INSTALL4J_JAVA_HOME

and that didn't do anything sadly. 

**OS**
Manjaro Linux

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment] 2021-11-02 07:54
The wiki is out of date. Use this thread https://forum.faforever.com/topic/12/linux-support?page=1

**Comment by coreybruce** [comment] 2021-11-02 09:12
I'm confused, how does this forum post help? it doesn't also give me a answer to the issue.

Could you please give me a straight direct answer on how to fix this?

**Comment by Sheikah45** [comment] 2021-11-02 09:55
That forum post is the main location for discussion on setting up the client in linux. I do not run nor support the client in linux so cannot answer your issue personally and right now their are no developers who support it for linux.

That thread also contains scripts and instructions for installing the client in linux that other users have found. You are probably best off making a message in that thread.

**Comment by Brutus5000** [comment] 2021-11-02 11:18
You misinterpret the error message. It's not complaining about missing Java, but about wrong version. Effectively duplicate of https://github.com/FAForever/downlords-faf-client/issues/2298

**Closed as completed by Brutus5000** 2021-11-02 11:18 UTC
Labels: bug, linux

**Comment by Askaholic** [comment] 2021-11-02 17:23
I actually set up the client on Manjaro yesterday with adopt OpenJDK 15 and it worked fine.

**Comment by coreybruce** [comment] 2021-11-02 23:15
> I actually set up the client on Manjaro yesterday with adopt OpenJDK 15 and it worked fine.

What package did you use? where is openjdk15? also isn't this this being updated to support java 15?

**Comment by Askaholic** [comment] 2021-11-03 00:20
I downloaded Adopt OpenJDK 15 from the archive page that Sheikah posted in this forum thread:

https://forum.faforever.com/topic/1754/installing-on-linux-with-java-15?_=1635898690721

Here’s the link: https://adoptopenjdk.net/archive.html
