### ISSUE TITLE
Add persistency to the map selected when creating a game

### ISSUE THREAD

**Issue by obydog002** [FAForever/downlords-faf-client#3184] opened 2024-05-28 12:27 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the Create game dialog doesn't save the map selected whens starting a game or cancelling the dialog.

**Describe the solution you'd like**
It would be nice if it remembered which map was previously selected when opening the dialog

**Comment by Sheikah45** [comment] 2024-05-28 12:29
Duplicate of #3156

**Closed as completed** 2024-05-28 12:29 UTC
