### ISSUE TITLE
Downloading/Update FAF game in background after launch client

### ISSUE THREAD

**Issue by KionX** [FAForever/downlords-faf-client#1629] opened 2020-03-22 17:09 UTC
Launch the client, select a game , click Join, and wait for the game to download\update(sometimes for a long time)
It also happens that you only need to download\update.

At least the "Update now" button.
Or option "Autoupdate"

**Comment by Katharsas** [comment] 2020-03-22 18:27
Please not automatically or optional.

**Comment by 1-alex98** [comment] 2020-03-22 20:00
not sure if that's good it might harm a users internet connection

**Comment by KionX** [comment] 2020-03-22 20:42
At least the "Update now" button.
Or option "Autoupdate"

**Comment by 1-alex98** [comment] 2020-03-24 17:27
I dont see a need for this the client checks on start up.

**Comment by KionX** [comment] 2020-03-24 19:54
Launch the client, select a game , click Join, and wait for the game to download\update(sometimes for a long time)
It also happens that you only need to download\update.

**Comment by Katharsas** [comment] 2020-03-24 20:10
Ok so this issue is about FA game updates, not client updates.
That might be a good idea.

And we really need a way to cache multiple updates at once without redownloading whenver an old replay is started and then redownloading when trying to join a game after that.

**Comment by Brutus5000** [comment] 2020-03-28 21:39
The whole featured mod handling should be rethought. This issue asks to fix a symptom instead of the cause.

**Why do you want to auto-download this stuff in the background?**
Because it takes a while.
**Why does it take so long?**
Because it's almost 50mb on each patch.
**Why do we need to download 50mb of patch with every new release if only a few kb have changed?** Because the patcher sucks. 
**Why is there no improved patcher?**
Because the zipping of folders makes this incredibly hard and inperformant. (I worked on this for over half a year and gave up.)
**Why do we have this weird zip structuce?**
I don't know. If we can get rid of this we have a better chance of improving the patcher.

**Comment by KionX** [comment] 2020-03-28 21:48
> This issue asks to fix a symptom instead of the cause.

> Why is there no improved patcher?
> Because the zipping of folders makes this incredibly hard and inperformant. (I worked on this for over half a year and gave up.)

What should I do?

All that remains is to use the unpacked files.
Arrange the builds in different folders.
Mount them from init_*.lua
Update with diff patches.
Is it possible?

**Comment by 1-alex98** [comment] 2020-03-29 00:23
Well i am closing this. I see it as @Brutus5000 yes updating is fucked and it needs a prper patcher

**Closed as completed by 1-alex98** 2020-03-29 00:23 UTC

**Comment by BlackYps** [comment] 2020-03-29 10:55
I just want to add that it is very possible to have the game load the files from ordinary folders. You just have to name the folder like the archive. At the moment it produces errors when starting the game with the client (because of the checksums, i think), but when launching with the exe it works.
Probably nobody dared to not use the zipping of the folders, because nobody knew why it existed.

**Comment by 1-alex98** [comment] 2020-03-29 11:21
This is intertesting so u mean that the zip things are not needed at all

**Comment by 1-alex98** [comment] 2020-03-29 11:22
Well the files are stored as zips on the server

**Comment by 1-alex98** [comment] 2020-03-29 11:26
Acctually @micheljung had a patchr of his own in place that just used git and the GitHub repo for the patching. Also without any zip files. There were three major disadvantages tho. 1. The init.lua was generated from the mod-info.lua and that broke occasonally. 2. ppl did not care to make tags in the github repo so that it also broke more often and as dfc had 5% user share the fa repo maintainers did not care to much breaking the client for days. 3.Sometimes there were funny exceptions because some file handles were left open, so that in some cases you had to restart your PC which was super annoying.   So in the end we just got rid of the git patcher BUT it was super fast and lightweight @BlackYps

**Comment by BlackYps** [comment] 2020-03-29 16:08
1. deploying the init lua is broken atm anyway https://github.com/FAForever/fa/issues/2972
2. This should be fixed with the proper using of branches that we have now, right?
3. Can't really comment on that

Of course the current rolling out of downloads has to be changed big time. I don't know how much work that is. But if downlord already had a mostly working git patcher I think it should be quite doable.
