### ISSUE TITLE
Local Replay Vault not refreshed after games played

### ISSUE THREAD

**Issue by andreasley** [FAForever/downlords-faf-client#1506] opened 2019-11-06 19:03 UTC
**Describe the bug**
After the local replay vault has been loaded once, it is never refreshed to include additional games. The only way to refresh it seems to be to restart the client, which does work reliably to display all recent replays.

**To Reproduce**
1. Open client
2. Show local replay vault
3. Play a game
4. Show local replay vault 

**Expected behavior**
The replays of all recent games should be displayed.

**OS / Version**
Windows 10, Client v1.0.0

**Comment by Brutus5000** [comment] 2019-11-06 19:29
Duplicate of https://github.com/FAForever/downlords-faf-client/issues/1141

**Closed as completed by Brutus5000** 2019-11-06 19:29 UTC
Labels: bug
