### ISSUE TITLE
"port check server is down, tell downlord"

### ISSUE THREAD

**Issue by wsargent** [FAForever/downlords-faf-client#184] opened 2016-01-28 18:53 UTC
Running 0.6.0-alpha, and there is a notification in the top right with this message.

There is also a bottom menu saying "connectivity unknown" -- right clicking shows help popup menu, but no screen comes up.  

There is an icon at the top left with wings and a down arrow -- clicking on that shows "Support" / "Settings" / "Feedback".  "Support" and "Feedback" do nothing.  Settings brings up a settings box.

**Comment by micheljung** [comment] 2016-01-28 18:59
Can you please send me your log file? (C:\ProgramData\FAForever\logs\downlords-faf-client.log)

**Comment by wsargent** [comment] 2016-01-28 19:04
Sure, how do you want it?  I'd use gist.github.com, but it's 160k.

**Comment by micheljung** [comment] 2016-01-28 19:06
You seem to be a developer, I guess you can identify the stack trace? :D That's all I need. Otherwise just the most recent logs ;)

**Comment by wsargent** [comment] 2016-01-28 19:19
```
10:46:48.151 [pool-2-thread-7] INFO  c.f.client.update.CheckForUpdateTask - Current version is 0.6.0-alpha, newest version is v0.6.0-alpha
10:46:48.294 [pool-2-thread-9] INFO  c.f.client.upnp.WeUpnpServiceImpl - Could not find a UPnP capable gateway
10:46:48.977 [JavaFX Application Thread] INFO  c.f.c.c.ConnectivityServiceImpl - Port check failed
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.CompletableFuture.uniRelay(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) [na:1.8.0_45]
	at com.faforever.client.task.TaskServiceImpl.lambda$submitTask$380(TaskServiceImpl.java:30) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.task.TaskServiceImpl$$Lambda$453/21706477.handle(Unknown Source) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.EventHelper.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Task.fireEvent(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Task.setState(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable.lambda$call$497(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Task$TaskCallable$$Lambda$511/32136901.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/2874854.run(Unknown Source) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/20347561.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source) [jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication$$Lambda$38/28435073.run(Unknown Source) [jfxrt.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at com.faforever.client.connectivity.FafConnectivityCheckTask.runTestForPort(FafConnectivityCheckTask.java:124) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.connectivity.FafConnectivityCheckTask.call(FafConnectivityCheckTask.java:96) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.connectivity.FafConnectivityCheckTask.call(FafConnectivityCheckTask.java:31) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_45]
	... 1 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) [na:1.8.0_45]
	at com.faforever.client.connectivity.FafConnectivityCheckTask.runTestForPort(FafConnectivityCheckTask.java:111) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	... 11 common frames omitted
10:46:48.977 [pool-2-thread-5] INFO  c.f.c.c.FafConnectivityCheckTask - Testing public connectivity of game port: 6112
10:46:48.978 [pool-2-thread-5] DEBUG c.f.c.l.writer.JsonMessageSerializer - Writing to server: {"command": "InitiateTest","args": [6112],"target": "connectivity"}
10:46:50.144 [Thread-26] DEBUG c.f.c.legacy.AbstractServerAccessor - Message from server: ????
10:46:50.148 [Thread-26] WARN  c.f.c.remote.FafServerAccessorImpl - Could not deserialize message: ????
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "????"
	at com.google.gson.Gson.fromJson(Gson.java:822) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:775) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:724) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:696) ~[gson-2.3.1.jar:na]
	at com.faforever.client.remote.FafServerAccessorImpl.parseServerObject(FafServerAccessorImpl.java:347) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.onServerMessage(FafServerAccessorImpl.java:329) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.legacy.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:44) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl.access$600(FafServerAccessorImpl.java:89) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:197) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:173) [downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_45]
	at javafx.concurrent.Service.lambda$null$488(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Service$$Lambda$195/4436551.run(Unknown Source) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at javafx.concurrent.Service.lambda$executeTask$489(Unknown Source) [jfxrt.jar:na]
	at javafx.concurrent.Service$$Lambda$193/21500058.run(Unknown Source) [jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]
Caused by: java.lang.IllegalStateException: Not a JSON Object: "????"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[gson-2.3.1.jar:na]
	at com.faforever.client.legacy.ServerMessageTypeAdapter.deserialize(ServerMessageTypeAdapter.java:22) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.faforever.client.legacy.ServerMessageTypeAdapter.deserialize(ServerMessageTypeAdapter.java:16) ~[downlords-faf-client-0.6.0-alpha.jar:0.6.0-alpha]
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[gson-2.3.1.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:810) ~[gson-2.3.1.jar:na]
	... 19 common frames omitted
```

**Comment by micheljung** [comment] 2016-01-28 19:25
What, the server send a message `????`? No idea why it would do that. Is this reproducible?
But the error message is an old one, that needs to be updated :-)

Thank you :)

**Comment by wsargent** [comment] 2016-01-28 19:33
It's reproducible on my end.  

I used to get very odd connection drops on the python client as well 

* http://forums.faforever.com/forums/viewtopic.php?f=3&t=9540
* https://github.com/FAForever/client/issues/207

**Comment by micheljung** [comment] 2016-01-28 20:18
So it seems to be a server problem. Why did you close the issue in the server repo :-)

**Comment by wsargent** [comment] 2016-01-28 20:29
https://github.com/FAForever/client/issues/207 hasn't happened in a long while.

**Comment by wsargent** [comment] 2016-01-28 20:30
The server repo I didn't close, sheeo did: https://github.com/FAForever/server/issues/83

**Comment by Sheeo** [comment] 2016-01-29 11:18
@wsargent if you don't mind, please open a new issue on server with STR. I'll look into it asap.

**Comment by wsargent** [comment] 2016-02-25 19:02
Computer is dead, so I'll be out of action for a month...

**Comment by micheljung** [comment] 2016-06-21 14:26
no longer relevant

**Closed by micheljung** 2016-06-21 14:26 UTC
