### ISSUE TITLE
Allow kicking player who is not connected to chat [moderation]

### ISSUE THREAD

**Issue by Viba** [FAForever/downlords-faf-client#2437] opened 2021-12-09 18:17 UTC
Currently as a moderator you can only kick players from the game/lobby who are connected to chat, ie. you need to be able to right click on their name.

We need a similar function as in the py client where you can either type the name of the player directly, or search for players connected to the actual lobby server and kick them that way.

**Comment by NapMorax** [comment] 2022-02-18 17:29
Yes, please do: there is a large number of "game freezes" at the start where one player gets stuck at the "Waiting for Players to Connect" screen and the other is already in the game.

See replay: https://replay.faforever.com/16389827

This is what Cast_Away saw:

![image](https://user-images.githubusercontent.com/88119424/154732486-b9f143a7-e1bb-41ab-ae2f-a0cbf11cb692.png)


And this is what I saw:

![image](https://user-images.githubusercontent.com/88119424/154732528-062172f7-91e3-42a9-bfa2-298238e9fcc8.png)

Often the issue is recognized by the player who could not connect, they leave, but in this case a player refused to leave. The game counts as a loss for whoever leaves so it should likely get some attention from a moderator. I think the player who fails to connect should accept the loss here as it is not fair to the person who did not cause the issue.

**Comment by Sheikah45** [comment] 2022-02-18 18:52
@NapMorax that doesn't really have anything to do with this issue. This is specifically about the issue of not being able to select an action on a player if they are not connected in chat. 

Which actually might be fixed in the next release now that I think about it.

**Comment by Sheikah45** [comment] 2022-02-19 13:43
Fixed in #2418

**Closed as completed by Sheikah45** 2022-02-19 13:43 UTC
