### ISSUE TITLE
Movement bug when resizing  trough drag on top.

### ISSUE THREAD

**Issue by samuel-hxs** [FAForever/downlords-faf-client#753] opened 2018-02-12 21:18 UTC
When dragging for resizing it follows the mouse movement.
This happens while the client loads up and possibly in other places.

OS was Windows 10 and client was a binary one from slack.

**Comment by 1-alex98** [comment] 2018-02-14 23:33
Could you try to explain it again I did not get it :(?

**Comment by samuel-hxs** [comment] 2018-02-15 21:17
When the client starts there is a loding time.
In this time i wanted to resize the window.
When i resized the window by dragging from top border it moved and resized in height.

So when i started resizing the bounds were like  x:300 y:100 w:400 h:600.
After resizing it was about x:300 y:183 w:400 h:517.
While resizing it moved the window by the same amount the window got resized.

I think it could be resize and drag at the same moment, based on the window size.
Because the windows forms top border was ca 83px under the mouse after dragging.

P.S.
Not real numbers and i can not reproduce it because my pc is without os atm.

**Comment by 1-alex98** [comment] 2018-02-15 22:19
When resizing beyound the min sitze of the window this is whats happening but thats not bad is it?

**Comment by micheljung** [comment] 2018-02-18 17:18
The only case we can reproduce is that the height stays at 600px when resizing because we currently don't allow the window to be made smaller than the minimum size required to display all content.

The same thing happens if you resize in width from the left edge.
It might be possible to fix but as this has pretty much no effect on the client's usability it has such a low priority that it will probably never happen :)
However, we could reconsider whether we allow arbitrary client sizes. IIRC, I did that back in time but some users complained about it.

**Comment by micheljung** [comment] 2018-11-12 07:36
Fixed in 0.9.0-beta

**Closed as completed by micheljung** 2018-11-12 07:36 UTC
