### ISSUE TITLE
Remove game from list if the game started

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#463] opened 2016-12-29 15:54 UTC
Even if a game has started it is shown as a game that's available....

**Comment by axel1200** [comment] 2016-12-29 15:59
It still shows the game that I did play 20 min ago in the  "Play" Tab and if I join it (what a surprise) it give me the mewssage host left game....

**Comment by Geosearchef** [comment] 2016-12-29 16:00
As far as I have experienced from my testing with the game preview in private chat, the gameStatusProperty is set correctly, so I'd guess it's just a problem with the UI

**Comment by axel1200** [comment] 2016-12-29 16:01
Yeah it might need to be refreshed

**Comment by axel1200** [comment] 2017-01-11 16:49
Probably Server Issue

**Comment by micheljung** [comment] 2017-01-12 02:20
Duplicate of #435

**Closed by micheljung** 2017-01-12 02:20 UTC
Labels: bug, duplicate
