### ISSUE TITLE
When opening a .faffreplay file with client nothing happens

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#652] opened 2017-11-27 20:43 UTC
I downloaded a file externally and opened it with the client the client started but nothing happend.

**Comment by micheljung** [comment] 2017-11-29 15:42
I've been wondering how long it takes until someone realizes this.... took many months :D

**Comment by micheljung** [comment] 2018-05-01 11:33
Duplicate of #333

**Closed by micheljung** 2018-05-01 11:33 UTC
Labels: bug
