### ISSUE TITLE
Vault -> Local Replays: No values in column "Game type"

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#823] opened 2018-03-24 18:46 UTC
![local_replays_table_format](https://user-images.githubusercontent.com/37223176/37867616-a1fe7918-2f9b-11e8-9963-e09e57d2da38.png)

**Comment by 1-alex98** [comment] 2018-03-25 09:03
Duplicate of #732, ther is a Pr that fixes it already

**Closed as completed by 1-alex98** 2018-03-25 09:03 UTC
Labels: bug, duplicate

**Comment by micheljung** [comment] 2018-03-25 11:07
"Duplicate of #..." would help to know where :)

**Comment by germanicianus** [comment] 2018-03-25 13:27
Oh. But I would have expected that the issue ("bug") stays open until the pull request ("fix") is merged ("checked-in"). Maybe that's just still Bugzilla and SVN thinking of myself.

**Comment by 1-alex98** [comment] 2018-03-25 15:25
I always do it this way

**Comment by micheljung** [comment] 2018-04-14 10:58
Closing duplicates is common practice, the initial issue stays open
