### ISSUE TITLE
Average rating is not re-calculated after someone disconnects

### ISSUE THREAD

**Issue by klaviqula** [FAForever/downlords-faf-client#2303] opened 2021-07-10 11:13 UTC
**Describe the bug**
Average rating is not re-calculated after someone disconnects

Such as: average of (1500,700) =1100
when 700 disconnects it still shows 1100 instead of 1500

**Expected behavior**
It should recalculate after disconnect

**OS**
Windows10

**Comment by Sheikah45** [comment] 2021-07-10 11:14
Where is the average rating display that you are talking about?

If it is after a game has started that shouldn't change.

**Comment by klaviqula** [comment] 2021-07-10 11:15
> Where is the average rating display that you are talking about?

Play/ Custom Games
Not after game starts

**Comment by Sheikah45** [comment] 2021-07-10 11:18
Does it not change consistently because it does when I run it?

**Comment by klaviqula** [comment] 2021-07-10 11:20
![test](https://user-images.githubusercontent.com/54857736/125161245-e3969d80-e189-11eb-9f42-63923d04b300.JPG)
I am 1500. 1400 guy joined, average changed to 1400. He disconnected, but average didnt change back to 1500.

**Comment by Sheikah45** [comment] 2021-07-10 11:23
Probably related to a bug with the teams I had to fix earlier. If you have the log file I can confirm.

**Comment by klaviqula** [comment] 2021-07-10 11:28
Its a FFA map,it might be about teams as you said.Which log should i send? There are many files in C:\ProgramData\FAForever\logs

**Comment by Sheikah45** [comment] 2021-07-10 11:31
Client.log

**Comment by klaviqula** [comment] 2021-07-10 11:31
[client.log](https://github.com/FAForever/downlords-faf-client/files/6795138/client.log)

**Comment by Sheikah45** [comment] 2021-07-10 11:37
Yeah it is the same issue. Should be fixed in the next release.

Fixed by #2297

**Closed as completed by Sheikah45** 2021-07-10 11:37 UTC
Labels: bug

**Comment by micheljung** [comment] 2021-07-16 11:15
@Sheikah45 When adding a milestone to an issue, the issue title will be used to generate the changelog. Therefore, to get an informative changelog, please reword issue titles accordingly.
