### ISSUE TITLE
Upload popup did not show full extent while uploading second map in a row

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#578] opened 2017-08-15 15:53 UTC
When i was about to upload multiple maps in a row to the vault, i had to refaf for every second map to display the upload popup correctly.

Thats how it looks like:
![image](https://user-images.githubusercontent.com/28671151/29323876-8466d038-81e2-11e7-9bed-40d174dbf3d1.png)

**Comment by axel1200** [comment] 2017-10-01 14:09
duplicate of #525

**Comment by axel1200** [comment] 2017-11-08 22:49
Can not be reproduced...
Please try the beta Version of the client when it is released. If this does not fix the issue pls reopen.

**Comment by axel1200** [comment] 2017-11-08 23:40
First the loading bar is shown then the actual UI but the window is not resized

**Comment by axel1200** [comment] 2017-11-15 20:25
Did manage but then the Pane does not resize wehen the window is resized

**Comment by Sheikah45** [comment] 2021-01-17 21:27
Can no longer reproduce

**Closed by Sheikah45** 2021-01-17 21:27 UTC
Labels: bug, in progress
