### ISSUE TITLE
[ Linux ] [ v0.9.3-beta ] links in chat do not respect default application

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1106] opened 2019-02-09 15:29 UTC
under linux with FAF in aeolus, FAF opens links with chrome instead of chromium, my default app  : 
![screenshot from 2019-02-09 16-25-52](https://user-images.githubusercontent.com/5132359/52522569-63ea0900-2c87-11e9-9696-27f1aac37b78.png)

this is weird because other app that can open links, such as steam or file browser correctly open up chromium. FAF is the only app for which this happens.

I've tried resetting the default app but this did nothing. it's not that big a deal it's just another one of those behaviors for which FAF isn't really system agnostic.

**Comment by 1-alex98** [comment] 2019-02-22 18:21
Probably the java Routine we use decides so

**Comment by TheBlueTroll** [comment] 2019-03-31 03:51
soo, good news, ive got a good idea of why its not working right, but i haven't figured out how to fix it yet. the problem basically stems from the fact that its not calling xdg-open.

xdg-open is on Ubuntu, (and i assume most Ubuntu based systems, such as mint ect.) a program for automagically opening a uri with the appropriate program. the idea being to solve the problem of the absolute convoluted mess that is mimetypes on Linux systems. essentially, xdg-open http://google.com will open the link with the appropriate browser, as set in the user's ~/.config/mimeapps.list and other places.

i don't know quite yet whats its calling, but because its not calling xdg-open, its not using the system default. 

I now suspect its not calling xdg at all, and its calling down the list as found at  
https://github.com/javafxports/openjdk-jfx/blob/8fab8207ac875dea9e564bd25db3b23272b84379/modules/javafx.graphics/src/main/java/com/sun/javafx/application/HostServicesDelegate.java#L125
as if you skip the first option, it will prioritize Chrome above Firefox, which is exactly what happened when i installed Chrome, and confirmed that Firefox was still the default.

the only thing i can think of is that the library is older then 30 November 2018 when xdg-open was added to the top of the list.

Yep found it, the Javafx version 11.0.2 LongTermSupport was release was 6th of November, 2018, the patch that added xdg to the list was on the 30th. so javafx doesn't respect system defaults at all, instead just goes down the list linked before skipping over xdg-open. 
it "could" be fixed by updating javafx to a newer version that includes the fix, but that could introduce other bugs. and alot of possible headache and effort for the developers for a fairly low value bug. also axel1200 is right, it was the java Routine.

Edit: Cleaned up the writing, split the sentences up, added further explanation on how i got my answers.

**Comment by 1-alex98** [comment] 2020-02-29 19:01
Well we plan going higher java fx version so this will eventually be fixed by time

**Closed as completed by 1-alex98** 2020-02-29 19:01 UTC
