### ISSUE TITLE
UI - Chat - Showing dialogue for icon choose, when there is no user icon

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#964] opened 2018-09-15 11:26 UTC
![strange-dialogue-at-chat](https://user-images.githubusercontent.com/26487134/45585793-e7771800-b8ea-11e8-8208-e99bfe6f9a77.png)

**Comment by germanicianus** [comment] 2018-09-21 08:43
Duplicate of issue #800 which is fixed with v0.9.0-beta.

**Closed as completed** 2018-09-21 08:44 UTC
Labels: duplicate
