### ISSUE TITLE
Linux: client "freezes" on the play tab

### ISSUE THREAD

**Issue by goteksc** [FAForever/downlords-faf-client#1353] opened 2019-07-17 18:42 UTC
[system specs and distro](https://gist.github.com/GotekSC/c74f0c5db7c404bf9ee93e113a329e1a) | client installed through the [AUR package](https://aur.archlinux.org/packages/downlords-faf-client/)

The play tab poses problems for me. When the client boots directly into the play tab, after the first few clicks on the buttons *inside* the tab, it ceases to respond. When I put the window in the background (switch to another tab or workspace in i3-wm), while leaving the client on the play tab, the window will be completely white when I come back to it.

Even in the unresponsive state, I can still switch to another tab like `News`, `Chat` etc. they all work properly as far as I can see.

**Comment by goteksc** [comment] 2019-07-18 15:57
Terminal output when trying in a floating window manager (xfce)

```
2019-07-18 17:43:13.190  WARN 31677 --- [lication Thread] javafx.beans                             : Exception while evaluating binding
java.lang.NullPointerException: null
	at com.faforever.client.player.Player.lambda$setGame$0(Player.java:261) [downlords-faf-client-0.10.7.jar:0.10.7]
	at javafx.beans.binding.Bindings$6.computeValue(Bindings.java:358) ~[javafx-base-11-linux.jar:na]
	at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:151) [javafx-base-11-linux.jar:na]
	at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:49) [javafx-base-11-linux.jar:na]
	at javafx.beans.property.ObjectPropertyBase.unbind(ObjectPropertyBase.java:185) [javafx-base-11-linux.jar:na]
	at com.faforever.client.player.Player.setGame(Player.java:257) [downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.player.PlayerService.updateGameDataForPlayer(PlayerService.java:179) [downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.player.PlayerService.lambda$updateGamePlayers$4(PlayerService.java:154) [downlords-faf-client-0.10.7.jar:0.10.7]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at com.faforever.client.player.PlayerService.updateGamePlayers(PlayerService.java:152) [downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.player.PlayerService.updateGameForPlayersInGame(PlayerService.java:112) [downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.player.PlayerService.onGameUpdated(PlayerService.java:95) [downlords-faf-client-0.10.7.jar:0.10.7]
	at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[guava-27.0-jre.jar:na]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) ~[guava-7.0-jre.jar:na]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) ~[guava-27.0-jre.jar:na]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.0-jre.jar:na]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67) ~[guava-27.0-jre.jar:na]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108) ~[guava-27.0-jre.jar:na]
	at com.google.common.eventbus.EventBus.post(EventBus.java:212) ~[guava-27.0-jre.jar:na]
	at com.faforever.client.game.GameService.createOrUpdateGame(GameService.java:654) ~[downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.game.GameService.onGameInfo(GameService.java:604) ~[downlords-faf-client-0.10.7.jar:0.10.7]
	at com.faforever.client.game.GameService.lambda$afterPropertiesSet$34(GameService.java:575) ~[downlords-faf-client-0.10.7.jar:0.10.7]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[javafx-graphics-11-linux.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277) ~[javafx-graphics-11-linux.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
```

**Comment by 1-alex98** [comment] 2019-07-18 18:00
Well the java.lang.ArrayIndexOutOfBoundsException sounds interesting do u have more on the in the log?

**Comment by 1-alex98** [comment] 2019-07-18 18:02
Also What java version are u using?

**Comment by 1-alex98** [comment] 2019-07-18 18:03
Can not open the "system specs and distro " link

**Comment by 1-alex98** [comment] 2019-07-18 18:07
try using oracle 10.0.2 that is what all the windows people run with

**Comment by goteksc** [comment] 2019-07-19 08:31
Content of the specs and distro link: https://gist.github.com/GotekSC/c74f0c5db7c404bf9ee93e113a329e1a
I installed the AUR package, so naturally `jre10-openjdk 10.0.2.u13-2` got installed as its dependency.

I'm trying to procure a bigger log with
`$ downlords-faf-client > faf-log` 
But it stops redirecting to the file after the exceptions start. In the linux support thread on the faf forum the maintainer of the AUR package [told me this is a known bug that got fixed in a recent commit.](http://forums.faforever.com/viewtopic.php?f=2&p=176419#p176419)

**Comment by 1-alex98** [comment] 2019-07-22 07:51
AUR package... did not know there was something like that

**Comment by kokx** [comment] 2019-09-02 20:21
I'm having this exact issue with 0.10.7. Both when installing manually following the instructions from the wiki for Linux, and using the [AUR package](https://aur.archlinux.org/packages/downlords-faf-client/).

I was able to capture an error log and the regular startup messages: https://gist.github.com/kokx/dcc04d569057b0f2d1e1cc96055303c6

I did this by executing:

```sh
$ downlords-faf-client > messages.log 2> errors.log
```

Note that I tried this under both i3wm and Xfce, I get the same errors under both.

**Comment by 1-alex98** [comment] 2019-09-03 08:19
no idea might be cuased using open jdk

**Comment by kokx** [comment] 2019-09-03 16:21
I downloaded the Oracle JDK 10 for this, and with the Oracle JDK I'm getting the same errors. Again, tried under both i3 and Xfce.

If you want the log using the Oracle JDK, here it is: https://gist.github.com/kokx/d865fad4864121aefffbc0fa3146fc26 but as I said, it isn't much different.

**Comment by germanicianus** [comment] 2019-09-05 08:13
kokx, the log you linked shows an ArrayIndexOutOfBoundsException in com.sun.prism.impl.GlyphCache which could be caused by a font according to these statements:
https://github.com/javafxports/openjdk-jfx/issues/287#issuecomment-441353824
https://bugs.openjdk.java.net/browse/JDK-8189092

Have a look at the Play tab which font is used there. I assume it’s your system font. Try to change it to a commonly used one, maybe even a Windows font like Tahoma.

**Comment by kokx** [comment] 2019-09-07 11:19
Thanks for the help so far germanicianus, unfortunately I haven't been able to figure out what font is used on the Play tab, but it looks like it would be my default sans-serif font, which is `Bitstream Vera Sans`.

Changing this system-wide on Xfce to `Tahoma` didn't change the FAF client font, so I assume it's getting it differently.

Is there a specific (type of) font that the client or JavaFX is looking for? For example, I could configure fontconfig to give a different font if asked for `sans-serif` or `serif` fonts, but the FAF client doesn't seem to be asking for either of them. So if it is asking for something more specific, I could try changing that.

**Comment by kokx** [comment] 2019-09-07 11:28
Looking around a bit more on how fonts are managed with JavaFX, I found [this page](https://wiki.openjdk.java.net/display/OpenJFX/Font+Setup). Where they said the java launch options could be changed to ignore fontconfig, by adding this:

`-Dprism.useFontConfig=false`

So I changed the bash file for starting the FAF client to include the above in the Java launch options. Using the above, the bug does not occur anymore, not even on i3.

**Comment by 1-alex98** [comment] 2019-09-07 12:01
I think we have your own font

**Comment by germanicianus** [comment] 2019-09-07 16:39
@kokx Good the hear. So it’s really a font issue - at least on Linux. Please add `-Dprism.debugfonts=true` to your launch options to get info about which fonts are chosen once with and once without `-Dprism.useFontConfig=false`.

**Comment by 1-alex98** [comment] 2019-09-07 18:23
So this means we should change our font?

**Comment by 1-alex98** [comment] 2019-09-07 18:26
Seems like we use Roboto

**Comment by germanicianus** [comment] 2019-09-08 14:30
@axel1200 I assume there are more people using Linux who have no problems. So there has to be at least one more reason why kokx is experiencing this issue. This is why I asked for the fonts debug log which lists the mapping of fonts.

**Comment by kokx** [comment] 2019-09-08 16:57
Okay, so I got quite a bit more information:

First, using the `-Dprism.debugfonts=true` does not show a font mapping, since it somehow causes a NullPointerException. Which you can see here: https://gist.github.com/kokx/18c8f70a90825c4a27296246844fdb38. Note that this is with the Oracle JDK, and is both with the `-Dprism.useFontConfig=false` option and without.

Secondly, changing to OpenJDK will not even allow me to boot the application anymore, when I pass the `-Dprism.useFontConfig=false` option. It does give me a startup error in a popup, and immediately quits when I click 'OK': https://gist.github.com/kokx/82e8b35ce18d8b17686b29e027045da8. I guess this happens because with OpenJDK it does not find the fonts somehow. They might be distributed with the Oracle JDK.

I also tried installing the Roboto font locally, and not passing the fontconfig option. But this did not change anything, and gives the original error.

**Comment by Lindenk** [comment] 2019-09-08 17:11
I'm also experiencing this issue exactly as described.

I'm also using Arch and installed the [downlords-faf-client](https://aur.archlinux.org/packages/downlords-faf-client/#comment-707359) packages from the aur. My window manager is i3 if that makes any difference.

[Here's a list of my installed fonts](https://gist.github.com/Lindenk/dbc5e392c9de96f017ce89cd7b71acd0)

**Comment by Lindenk** [comment] 2019-09-08 17:14
[Here's a snapshot of my console errors when clicking on the 'Play' tab](https://gist.github.com/Lindenk/4e030ef57340c81dae9b93f4af8e2eff)

**Comment by germanicianus** [comment] 2019-09-08 18:04
Ok. That is strange. At least we have a known workaround when using the AUR package and hitting this issue: Use the Oracle JRE and add the Java launch option `-Dprism.useFontConfig=false`.

**Comment by kokx** [comment] 2019-09-08 18:11
Actually I was not using the AUR package for that. It was a complete manual installation. You could probably adjust the AUR package to get it to work though (since it doesn't do much different than provide a launch script).

**Comment by 1-alex98** [comment] 2019-09-08 22:23
I am out. If you find out what I need to do tell me :D

**Comment by Katharsas** [comment] 2019-09-09 11:12
Somebody could try running the client with JavaFX 11 or 12, maybe the issue was fixed somewhere (you will need to build the client yourself with https://github.com/FAForever/downlords-faf-client/pull/1325).

**Comment by germanicianus** [comment] 2019-09-11 04:47
@kokx and @Lindenk, I don’t think it makes a difference but you could try to run the client with the script provided by me in https://github.com/FAForever/downlords-faf-client/issues/1080#issuecomment-451610177, but you need to convert it (back) to a bash script and adapt the version(s) because it’s nearly a year old. If you want, I can provide the bash version.

**Comment by Wesmania** [comment] 2019-10-17 20:19
Another workaround that works for me:
```
-Dprism.order=sw
```

**Comment by iczero** [comment] 2019-10-26 02:35
This problem happened with me. I fixed it by unchecking the "Show private games" box blindly. Whenever it is selected, the Play tab freezes completely, but unchecking it makes it usable again.

For those of you trying to find the checkbox, it is directly under the V in the Vault tab.

**Comment by 1-alex98** [comment] 2019-10-27 10:05
oh yeah that makes totally sense @iczero not sure if the read the java fx bug but that is related to  unicode in list views and the lock symbol in that list is unicode(the one for private games.

**Comment by 1-alex98** [comment] 2019-10-27 10:06
Well we could just make it an X on linux instead of 🔒

**Comment by 1-alex98** [comment] 2019-10-27 10:09
Also it seems java fx guys fixed it 
![grafik](https://user-images.githubusercontent.com/19996713/67632953-26c3b680-f8aa-11e9-951f-01176858ba89.png)
but we will see if we can update to version 14 and i think 14 is not yet release so we will need to wait some month

**Comment by 1-alex98** [comment] 2019-10-27 10:12
also if one of u is really motivated he could ty get a build with java fx 14 and use that unoffical build for the time beng till we change to java fx 14

**Comment by 1-alex98** [comment] 2020-01-12 18:39
@Katharsas why did you unpin it ? 🤔

**Comment by Katharsas** [comment] 2020-01-12 19:16
That must have been a misclick, i didnt even know Github had pinning.

**Comment by Katharsas** [comment] 2020-03-06 22:56
JavaFX 14 was released today:
https://github.com/openjdk/jfx/blob/9db2ff258fde2a60b1494857e2cacbf76791f4aa/doc-files/release-notes-14.md

**Comment by 1-alex98** [comment] 2020-03-09 21:01
I am curious on whether we can use javafx 14 with jdk 11, because for javafx 13 this is possible

**Comment by Katharsas** [comment] 2020-03-12 16:57
Should work:
>JavaFX 14 requires JDK 11 or later.

**Comment by 1-alex98** [comment] 2020-03-14 10:28
nice we should consider this

**Comment by 1-alex98** [comment] 2020-03-14 10:29
Maybe we wait till 14.01 or something to really bad bugs introduced are noticed and fixed

**Comment by Katharsas** [comment] 2020-06-14 03:35
14.0.1 is out and work has begun on 15, we should try to switch

oh ok seems we are blocked by https://github.com/FAForever/downlords-faf-client/issues/1756

**Comment by 1-alex98** [comment] 2020-09-26 08:48
We are still on java fx 11

**Comment by 1-alex98** [comment] 2020-09-26 08:54
Tho we have a branch with jfx 14 and we might update soon TM

**Comment by tatsujb** [comment] 2020-10-04 11:56
@Lindenk @kokx @germanicianus @GotekSC  you all assumed this github repo is the maintainer of the AUR.

It's not.

you need to find the maintainer of the AUR and notify him because whatever they change here isn't going to affect you guys if the AUR guy doesn't remake his package.

**Comment by dcelasun** [comment] 2020-10-08 06:58
Hey, so I'm the maintainer of the AUR package. I have never experienced this issue and nobody ever mentioned it in the comments :( 

Nevertheless, I've updated the package to use Oracle's JDK 14 to [work around an issue](https://github.com/FAForever/downlords-faf-client/issues/1957) with Arch's OpenJDK so maybe try that out and see if it works for you.

**Comment by 1-alex98** [comment] 2021-03-24 15:33
We could probably close this right?

**Comment by Sheikah45** [comment] 2021-06-05 10:52
Solved see comments

**Closed as completed by Sheikah45** 2021-06-05 10:52 UTC
Labels: bug, S2 major
