### ISSUE TITLE
Make hosts configurable

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#477] opened 2017-01-18 16:43 UTC
Currently, all URLs and hosts are configured in the application.properties, making it difficult to change by the user.
Move those to the preferences file.

**Comment by axel1200** [comment] 2017-01-28 23:17
We should then Think about a button to reset settings, as users might misset their settings!

**Comment by 1-alex98** [comment] 2018-03-10 20:52
Duplicate of #761

**Comment by micheljung** [comment] 2018-03-17 17:07
Not exactly; The current solution only allows to change the setting for the current session, it doesn't store it in the preferences file.

Preferably, we keep a history in the preferences file and convert the current text fields to ComboBoxes so users can easily switch.
I'd also like that it remembers the last selection. If it's non-default, the form is displayed automatically. If not, it's hidden.

**Closed** 2020-02-29 19:24 UTC
Labels: enhancement
