### ISSUE TITLE
the 1v1 timer for matchmaking is 62 minutes 

### ISSUE THREAD

**Issue by KhaldounN** [FAForever/downlords-faf-client#2076] opened 2020-12-26 18:43 UTC
**Describe the bug**
the 1v1 timer for matchmaking is 62 minutes 

**To Reproduce**
 just login to FAF 

**Log or error message**
none 

**Expected behavior**
2 -3 minutes timer 

**Screenshots**
![image](https://user-images.githubusercontent.com/71594059/103157370-6f2e7b00-47b2-11eb-92d1-6ecdf3f8448b.png)

**OS**
 Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment] 2020-12-26 18:43
This happens when your system time is off from the faf server time

**Comment by KhaldounN** [comment] 2020-12-26 18:46
hi

thanks for the quick response.

how do I fix it ?

**Comment by Brutus5000** [comment] 2020-12-26 18:46
@Sheikah45 Are you sure? I am in timezone Europe/Berlin, server is UTC. I don't have any issues.

**Comment by Sheikah45** [comment] 2020-12-26 18:47
Yeah it is also noted in #1622. And I mean the local system time not the timezone

**Comment by Sheikah45** [comment] 2020-12-26 18:48
So if the system time was manually set I know there can be issues

**Comment by KhaldounN** [comment] 2020-12-26 18:48
NVM I fixed it by syncing my time

**Comment by Sheikah45** [comment] 2020-12-26 18:50
Duplicate of #1622

**Closed as completed by Sheikah45** 2020-12-26 18:50 UTC
Labels: bug
