### ISSUE TITLE
Mod upload window can open too small to read content

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/downlords-faf-client#1008] opened 2018-10-31 22:58 UTC
I suggest a minimum size based on the normal content of the window. Resize-able is nice, but it shouldn't be invisible!

**Comment by 1-alex98** [comment] 2018-10-31 23:04
duplicate no idea what the issue number was gonna find it

**Comment by 1-alex98** [comment] 2018-10-31 23:05
duplicate of https://github.com/FAForever/downlords-faf-client/issues/578
well i mean same issue with mod and maps

**Closed as completed** 2018-10-31 23:05 UTC
