### ISSUE TITLE
Unable to start a coop campaign game

### ISSUE THREAD

**Issue by andriusch** [FAForever/downlords-faf-client#2670] opened 2022-04-19 01:22 UTC
**Describe the bug**
When I launch the coop campaign map through FAF client it opens lobby screen. However "Launch Game" button doesn't launch the game (after readying), nothing happens when I click it. Interestingly if I open "Options" most of the options seems to be missing and I can't leave the options screen neither by clicking "OK" nor "Cancel", only alt+f4 helps.

Hosting custom games works without problems. Playing campaign not through FAF client also works with no problems.

**To Reproduce**
- Open Co-Op tab
- Choose any map, enter name and password
- Click "Host Game"
- Click "Ready" after game starts
- Click "Launch Game", nothing happens

**Log or error message**
https://pastebin.com/rJ5kmPV6

**Expected behavior**
Expected to be able to play Co-Op campaign.

**Screenshots**
![image](https://user-images.githubusercontent.com/25230/163897549-ce460101-2a79-4f94-bc05-977f6d89b33d.png)
![image](https://user-images.githubusercontent.com/25230/163897238-21b61d14-b8f0-48fe-8681-9f8ed4d827c7.png)

**OS**
Linux

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment] 2022-04-19 01:24
Duplicate of #2318

**Closed as completed by Sheikah45** 2022-04-19 01:24 UTC
Labels: bug
